### ISSUE TITLE
Désactiver les code de tracking en preprod et local

### ISSUE THREAD

**Issue by Johnmgt** [gryzzlybot/gryzzlyio#8]

**Comment by aitva** [comment]
À premier vu il y a deux possibilités :
- avoir deux fichiers de config (`prod.yml` et `config.yml`) qui positionne une variable pour activer les codes de tracking
- utiliser `getenv` et positionner une variable d'environment pour détecter si on est en prod ou non
  cf : https://discourse.gohugo.io/t/development-production-workflow-revisited/218/6
